version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common && add-apt-repository ppa:webupd8team/java -y && apt-get update && echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && apt-get install -y oracle-java8-installer && apt-get clean
      - java -version
      - ls -al
      - sudo chmod 755 gradlew	
      - ./gradlew -version
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started
      - ./gradlew build --stacktrace --info
  post_build:
    commands:
      - echo Build completed
      - ls -al
artifacts:
  files:
    - authService/build/libs/authService-0.1.0.jar
    - authService/application.properties
    - productService/build/libs/productService-0.1.0.jar
    - productService/application.properties
    - helloWorldService/build/libs/helloworld-0.1.0.jar
    - helloWorldService/application.properties
    - appspec.yml
  discard-paths: no
