version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y gradle
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - gradle build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - authService/build/libs/authService-0.1.0.jar
    - productService/build/libs/productService-0.1.0.jar
    - helloWorldService/build/libs/helloworld-0.1.0.jar
  discard-paths: yes
