version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y gradle
      - apt-get install openjdk-8-jdk
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - gradle build
  post_build:
    commands:
      - echo Build completed on `date`
