version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common && add-apt-repository ppa:webupd8team/java -y && apt-get update && echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && apt-get install -y oracle-java8-installer && apt-get clean
      - java -version
      - ls -al
      - sudo chmod 755 gradlew	
      - ./gradlew -version
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started
      - ./gradlew build -x test --stacktrace --info
  post_build:
    commands:
      - echo Build completed
      - ls -al
artifacts:
  files:
    - authService/build/libs/authService-1.0.0-SNAPSHOT.jar
    - productService/build/libs/productService-1.0.0-SNAPSHOT.jar
    - helloWorldService/build/libs/helloworld-1.0.0-SNAPSHOT.jar
    - kafkaConsumer/build/libs/kafkaConsumer-1.0.0-SNAPSHOT.jar
    - kafkaProducer/build/libs/kafkaProducer-1.0.0-SNAPSHOT.jar
    - serviceDiscovery/build/libs/eureka-1.0.0-SNAPSHOT.jar
    - zuulApp/build/libs/zuul-1.0.0-SNAPSHOT.jar
  discard-paths: no
